### ISSUE TITLE
Make the data portal read-only

### ISSUE THREAD

**Issue by Fgerthoffert** [icgc-dcc/roadmap#6]
- [ ] Migrate Hadoop cluster
- [ ] Upgrade Elasticsearch
- [ ] Determine what files to keep

Note: Some changes might still happen after completion, but those would not require running the ETL

**Comment by b-f-chan** [comment]
Accidentally closed while testing new roadmap board.

**Comment by b-f-chan** [comment]
Accidentally closed while testing new roadmap board.
